services:
  Alma\SyliusPaymentPlugin\Payum\Action\StatusAction:
    public: true
    tags:
      - name: payum.action
        factory: alma_payments
        alias: payum.action.status

  Alma\SyliusPaymentPlugin\Payum\Action\ConvertPaymentAction:
    public: true
    arguments:
      $paymentDataBuilder: '@alma_sylius_payment_plugin.payment_data_builder'
    tags:
      - name: payum.action
        factory: alma_payments
        alias: payum.action.convert_payment

  Alma\SyliusPaymentPlugin\Payum\Action\CaptureAction:
    public: true
    tags:
      - name: payum.action
        factory: alma_payments
        alias: payum.action.capture

  Alma\SyliusPaymentPlugin\Payum\Action\RenderInPagePaymentAction:
    public: true
    tags:
      - name: payum.action
        factory: alma_payments

  Alma\SyliusPaymentPlugin\Payum\Action\RedirectToPaymentPageAction:
    public: true
    arguments:
      $logger: '@logger'
      $requestStack: '@request_stack'
    tags:
      - name: payum.action
        factory: alma_payments

  Alma\SyliusPaymentPlugin\Payum\Action\ValidatePaymentAction:
    public: true
    tags:
      - name: payum.action
        factory: alma_payments

  Alma\SyliusPaymentPlugin\Payum\Action\NotifyAction:
    public: true
    tags:
      - name: payum.action
        factory: alma_payments
        alias: payum.action.notify
