services:
  Alma\SyliusPaymentPlugin\Payum\Extension\RefundFailedPaymentExtension:
    public: true
    arguments:
      $api: '@alma_sylius_payment_plugin.bridge'
      $logger: '@logger'
      $requestStack: '@request_stack'
    tags:
      - name: payum.extension
        factory: alma_payments

  Alma\SyliusPaymentPlugin\Twig\AlmaExtension:
    public: true
    autowire: true
    arguments:
      $eligibilityHelper: '@alma.sylius_payment_plugin.helper.eligibility'
      $feePlansHelper: '@alma.sylius_payment_plugin.helper.fee_plans'
    tags:
      - name: twig.extension
