services:
  alma.sylius_payment_plugin.helper.eligibility:
    class: Alma\SyliusPaymentPlugin\Helper\EligibilityHelper
    arguments:
      $almaBridge: '@alma_sylius_payment_plugin.bridge'
      $eligibilityDataBuilder: '@alma_sylius_payment_plugin.eligibility_data_builder'