sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.gateway_configuration.alma_payments':
            form:
                template: '@AlmaSyliusPaymentPlugin/admin/payment_method/form/section/gateway_configuration/alma_payments.html.twig'
                priority: -100
        'sylius_admin.payment_method.update.content.form.sections.gateway_configuration.alma_payments':
            form:
                template: '@AlmaSyliusPaymentPlugin/admin/payment_method/form/section/gateway_configuration/alma_payments.html.twig'
                priority: -100
