services:
  alma_sylius_payment_plugin.registry.payment_data_builder:
    class: Sylius\Component\Registry\ServiceRegistry
    arguments:
      - Alma\SyliusPaymentPlugin\DataBuilder\DataBuilderInterface
      - payment data builder

  alma_sylius_payment_plugin.payment_data_builder:
    class: Alma\SyliusPaymentPlugin\DataBuilder\PaymentDataBuilder
    arguments:
      $buildersRegistry: '@alma_sylius_payment_plugin.registry.payment_data_builder'

  alma_sylius_payment_plugin.payment_data_builder.customer:
    class: Alma\SyliusPaymentPlugin\DataBuilder\CustomerDataBuilder
    tags:
      - name: alma_sylius_payment_plugin.payment_data_builder
        id: customer

  alma_sylius_payment_plugin.payment_data_builder.order:
    class: Alma\SyliusPaymentPlugin\DataBuilder\OrderDataBuilder
    tags:
      - name: alma_sylius_payment_plugin.payment_data_builder
        id: order

  alma_sylius_payment_plugin.payment_data_builder.addresses:
    class: Alma\SyliusPaymentPlugin\DataBuilder\AddressesDataBuilder
    tags:
      - name: alma_sylius_payment_plugin.payment_data_builder
        id: addresses

  alma_sylius_payment_plugin.payment_data_builder.shipping_info:
    class: Alma\SyliusPaymentPlugin\DataBuilder\ShippingInfoDataBuilder
    arguments:
      $calculators: '@sylius.registry.shipping_calculator'
      $methodsResolver: '@sylius.resolver.shipping_methods'
    tags:
      - name: alma_sylius_payment_plugin.payment_data_builder
        id: shipping_info

  alma_sylius_payment_plugin.payment_data_builder.cart:
    class: Alma\SyliusPaymentPlugin\DataBuilder\CartDataBuilder
    arguments:
      $router: '@router'
      $liipCacheManager: '@liip_imagine.cache.manager'
      $taxRateResolver: '@sylius.resolver.tax_rate'
    tags:
      - name: alma_sylius_payment_plugin.payment_data_builder
        id: cart
  alma_sylius_payment_plugin.eligibility_data_builder:
    class: Alma\SyliusPaymentPlugin\DataBuilder\EligibilityDataBuilder
    tags:
      - name: alma_sylius_payment_plugin.eligibility_data_builder
        id: eligibility
